g

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,16 +1,21 @@
 #!/usr/bin/env bash
-# Check if exactly 4 arguments were provided
+#thi bash script post a file to the home directory of the server
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
 
-if [ "$#" -ne 4 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+if ["$#" -ne 4]; then
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-# Assign arguments to variables
-FILE=$1
-IP=$2
-USER=$3
-KEY=$4
+scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"
 
-# Transfer the file using scp
-scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
+# Check if the SCP command was successful
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully."
+else
+    echo "Failed to transfer file."
+    exit 1
+fi
